name: Backend Package Update

on:
  repository_dispatch:
    types: [frontend-packages-published]

jobs:
  update-packages:
    name: Update Frontend Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Update packages
        uses: collaborationFactory/github-actions/.github/actions/backend-package-updater@feature/automate-frontend-pkg-integration
        with:
          branch: ${{ github.event.client_payload.branch }}
          actor: ${{ github.event.client_payload.actor }}
